[project]
name = "epubmetadataeditor"
version = "0.1.0"
description = "A simple Epub Metadata Editor"
authors = [
    { name = "T. E. Kalaycı" }
]
license = { text = "Apache-2.0" }
requires-python = ">=3.12"
dependencies = [
    "pycairo>=1.20.0",
    "PyGObject>=3.38.0",
    "lxml>=4.6.2",
]

[dependency-groups]
dev = [
    "autopep8",
    "black",
    "isort"
]

[project.scripts]
epub-editor = "main:main"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
